### PR TITLE
Corrected the typo in update.py

### LINKED ISSUE #187: typo: Correct the spelling of 'participants'
In https://github.com/coala/community/blob/master/gamification/process/update.py there is a typo.

The spelling of ```participants```  is written as ```particiapnts``` which needs to be corrected.
This would be a good newcomer issue

### PR DESCRIPTION
**Pull request by Priya997**
#187 Resolved

### CODE REVIEW

**Comment by shikharvaish28** [comment]
Please squash all the commits as one.

**Comment by Priya997** [comment]
Can you help me how to squash commits?

**Comment by shikharvaish28** [comment]
Try googling ```git rebase -i``` also known as ```interactive rebase```

**Comment by palash25** [comment]
@Priya997 just one thing that you should keep in mind the next time you make a PR be sure to checkout a new branch (your master should remain clean that will help you make a PRs if the master is clean and synced with the upstream master if you are looking to contribute in the long run). 

**So every PR will be made from a new branch.** :wink:

**Comment by Priya997** [comment]
@palash25 ok I will take care from next time. But this time can it be approved?

**Comment by palash25** [comment]
> But this time can it be approved?

I guess we can, but only maintainers merge the PRs so you are gonna have to wait.

**Comment by Priya997** [comment]
According to the link you provided "Should use the Fixes keyword if your commit fixes a bug, or Closes if it adds a feature/enhancement." Closes should be used.

**Comment by Dhiraj240** [comment]
@Priya997 For me it is showing the description of Shortlog anyways read the Shortlog description carefully given in the link.

**Comment by Priya997** [comment]
@Dhiraj240 So many different reviews @li-boxuan is saying add closes you are saying add close which one to follow?

**Comment by Dhiraj240** [comment]
@Priya997 Oh you took it in wrong way i thought you have read the guidelines but i was wrong so change Shortlog which means instead of ```update.py: Closes docstring typo``` use ```update.py: Close docstring typo ``` This is what shortlog meant to be.Please read the good commit message guidelines,link has been already shared by me.

**Comment by Priya997** [comment]
Hello, @jayvdb @Dhiraj240 did the changes. Please have a look

**Comment by jayvdb** [comment]
ack https://github.com/coala/community/pull/188/commits/fc87e9c2026dd06b336826083405c8c52de7beab

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by ayan-b** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
