### PR TITLE
ci: Use correct Python version specification

### PR DESCRIPTION
**Pull request by sks444**
3.6.2 is invalid (minor versions are not supported and trigger errors
on netlify, causing a fallback to a lower Python version than
supported), only 3.6 is allowed.
Fixes https://github.com/coala/community/issues/85

### CODE REVIEW

**Comment by jayvdb** [comment]
first work of commit message shortlog should be `runtime.txt`

**Comment by sks444** [comment]
@jayvdb, sorry for the trouble :(
it's done :)

**Comment by jayvdb** [comment]
ack https://github.com/coala/community/pull/86/commits/89197d8605d62de0e5eaac61be39704be11bc33a

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
