### PR TITLE
.coafile: Add Jinja bear for templates

### LINKED ISSUE #129: Add jinja bear to .coafiles
The templates are in jinja format.
We have a bear for those.

### PR DESCRIPTION
**Pull request by jakethakur**
Closes #129

### CODE REVIEW

**Review by jayvdb — CHANGES_REQUESTED** [review]
please turn off setting `check_end_labels` , so the bear doesnt emit so many errors.

e.g. https://travis-ci.org/coala/community/jobs/450422094#L4430

**Comment by jakethakur** [comment]
It seems like the errors are either to do with not being able to connect to openhub or errors in the jinja bear itself - is there anything I can do to fix these?

**Comment by jakethakur** [comment]
Hmm, I'm not sure that fixed anything. Any ideas?

**Review by jayvdb — CHANGES_REQUESTED** [review]
two changes required for jinja files ; see end of travis log.

ignore openhub errors

**Comment by jayvdb** [comment]
ping @jakethakur , time is running short ..

**Comment by jayvdb** [comment]
Damnit, `check_end_labels = False` wont work until coala releases a new version of the bears, and GitMate is using that new version of the bears.

**Pull request closed without merging**
