### PR TITLE
Fix netlify build issues

### PR DESCRIPTION
**Pull request by abhishalya**
This fixes some of the netlify build issues.
  * Changes the python version in runtime.txt

### CODE REVIEW

**Comment by KVGarg** [comment]
Check the bottom logs of netlify! They've provided a improvement to our build.sh file.

**Comment by abhishalya** [comment]
Let's get all of your fixes merged first.

**Comment by KVGarg** [comment]
to not get errors related to contributor model, we need to merge this first https://github.com/coala/community/pull/242

**Comment by abhishalya** [comment]
@KVGarg what seems to be the issue with netlify?

**Comment by KVGarg** [comment]
Checking!

**Comment by KVGarg** [comment]
Can you add a commit with pytest >= 4.6

**Comment by abhishalya** [comment]
But it shouldn't affect the netlify deploy right
>Can you add a commit with pytest >= 4.6

**Comment by KVGarg** [comment]
yes! just to get green for pytest which is failing in travis

**Comment by abhishalya** [comment]
@KVGarg If you have a pending PR here, you can add those changes... If there are other fixes I can do them here.

**Comment by KVGarg** [comment]
I believe the pytest has failed bcause we changes python version from 3.6 to 3.7

**Comment by KVGarg** [comment]
Lemme check locally building the repo, and re-pushing a PR to check what actual we need to do

**Comment by abhishalya** [comment]
Sure, let's take a break. I'll be merging again in some time.

**Comment by KVGarg** [comment]
@abhishalya another possible reason to get build fail is API limit hit. we are limited to 60 requests per hour

**Pull request merged**
