### PR TITLE
openhub/models.py: Fix str method

### PR DESCRIPTION
**Pull request by rohanrk**
self.project1 -> self.project for MostCommit model
self.project2 -> self.project for MostRecentCommit model

Closes https://github.com/coala/community/issues/116

### CODE REVIEW

**Comment by sks444** [comment]
@rohanrk, can you extend your commit body a bit further, like:
```
self.project1 -> self.project for MostCommit model.
self.project2 -> self.project for MostRecentCommit model.
```
And use `Fixes` for issue reference it was a bug.

**Comment by rohanrk** [comment]
I would have used 'fixes', but I think gitmate will yell at me because this issue isn't labeled as a bug. I'll amend.

**Comment by jayvdb** [comment]
ack https://github.com/coala/community/pull/125/commits/bc383fd6f60ad93f2105f872882d5fe7fde5e47d

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
